# Generated by Django 3.2.11 on 2023-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_transaction_id_order_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
